music/urls.py
from django.conf.urls import url
from . import views
app_name='music'
urlpatterns = [
    url(r'^$',views.IndexView.as_view(),name='index'),

    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
]

mywebsite/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from companies import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/',include('music.urls')),
    url(r'^stocks/',views.StockList.as_view())
]
#urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns=format_suffix_patterns(urlpatterns)

companies/models.py
from django.db import models

# Create your models here.
class Stock(models.Model):
    ticker=models.CharField(max_length=10)
    open =models.FloatField()
    close=models.FloatField()
    volume=models.IntegerField()
    def __str__(self):
        return self.ticker

music/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
    artist=models.CharField(max_length=250)
    album_title=models.CharField(max_length=500)
    genre=models.CharField(max_length=100)
    album_logo=models.FileField()
    def __str__(self):
        return self.album_title+' - '+self.artist
class Song(models.Model):
    album=models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type=models.CharField(max_length=10)
    song_title=models.CharField(max_length=250)
    is_favorite=models.BooleanField(default=False)
    def __str__(self):
        return self.song_title

companies/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from .models import Stock
from .serializers import StockSerializer
# Create your views here.
class StockList(APIView):
    def get(self,request):
        stocks=Stock.objects.all()
        serializer=StockSerializer(stocks,many=True)
        return Response(serializer.data)
    def post(self):
        pass

music/views.py
from django.views import generic
from .models import Album
class IndexView(generic.ListView):
    template_name="music/index.html"
    def get_queryset(self):
        return Album.objects.all()
class DetailView(generic.DetailView):
    model=Album
    template_name='music/detail.html'
    

music/templates/music/detail.html
<h1>{{album.album_title}}</h1>
<h2>{{album.artist}}</h2>
<img src="{{album.album_logo.url}}"></img>
{% if error_message %}
	<p><strong>{{error_message}}</strong></p>
{% endif %}

music/templates/music/index.html
{% load staticfiles %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<link rel="stylesheet" type="text/css" href="{% static 'BackgroundStyle.css'%}">

<nav class="navbar navbar-default">
	
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topnavbar">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="{% url 'music:index' %}">my music</a>
	</div>
	<div class="collapse navbar-collapse" id="topnavbar">
		<ul class="nav navbar-nav">
			<li class="">
				<a href={%url 'music:index'%}>
					<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>
					Albums
				</a>
			</li>
			<li class="">
				<a href="#">
					<span class="glyphicon glyphicon-music" aria-hidden="true"></span>
					Songs
				</a>
			</li>
		</ul>
		<form class="navbar-form navbar-left" role="search" method="get" action="#">
			<div>
				<input type="text" class="form-control" name="q" value="">
			</div>
			<button type="submit" class="btn btn-default">Search</button>
		</form>
		<ul class="nav navbar-nav navbar-right">
			<li class="">
				<a href="#">
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
					Add Album
				</a>
			</li>
			<li class="">
				<a href="#">
					<span class="glyphicon glyphicon-off" aria-hidden="true"></span>
					Logout
				</a>
			</li>
		</ul>
	</div>
</nav>
{% if object_list %}
	<ul>
		{% for album in object_list %}
		<li><a href="{% url 'music:detail' album.id%}">{{album.album_title}}</a></li>
		{% endfor %}
	
	</ul>
{% else %}
    <h3>you don't have any albums </h3>
{% endif %}